### ISSUE TITLE
change `chain_name` from inputbox to select inputbox

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/scaffold-move#10]
Money: `500 R`
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/12784118/212221618-5213e9d3-4cf7-4535-939c-5d3d352ce195.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/12784118/212221757-f3bec1a6-636f-4e83-9c0b-59fd050b1f97.png">

**Comment by itherunder** [comment]
🙋

**Comment by xiguakaoya** [comment]
🙋
