### ISSUE TITLE
Make the output of `get resource` pretty.

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/scaffold-move#7]
It's good to show the json prettier in `code tag` of markdown

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/12784118/202829152-944f0dff-5bc2-47a8-a657-133b5d0cf15c.png">

**Comment by Dream4ever** [comment]
done at https://github.com/NonceGeek/scaffold-move/commit/60495bcf9b112e9766ca5ed6c3724aa74ea9286d .
